apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresqlinstances.azure.platform.upbound.io
  labels:
    dbengine: postgres
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: azure.platform.upbound.io/v1alpha1
    kind: SQLInstance
  mode: Pipeline
  pipeline:
    - functionRef:
        name: upbound-configuration-azure-databasepostgres
      step: postgres
    - functionRef:
        name: crossplane-contrib-function-auto-ready
      step: crossplane-contrib-function-auto-ready
