apiVersion: azure.platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  name: configuration-azure-database-db-postgresql
  namespace: default
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        dbengine: postgres
  parameters:
    region: westus
    storageGB: 32 #Minimum value is 32
    version: "11"
    managementPolicies: ["*"]
    passwordSecretRef:
      name: psqlsecret
      key: password
    networkRef:
      id: configuration-azure-database #This field must match the Network XR spec.parameters.id
  writeConnectionSecretToRef:
    name: configuration-azure-database-db-conn-postgresql
