apiVersion: azure.platform.upbound.io/v1alpha1
kind: XSQLInstance
metadata:
  name: configuration-azure-database-db-postgresql
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      dbengine: postgres
  parameters:
    region: westus
    storageGB: 5 #Minimum value is 5
    version: "11"
    passwordSecretRef:
      namespace: default
      name: psqlsecret
      key: password
    networkRef:
      id: configuration-azure-database #This field must match the XNetwork XR spec.parameters.id
  writeConnectionSecretToRef:
    name: configuration-azure-database-db-conn-postgresql
    namespace: default
