apiVersion: azure.platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  name: configuration-azure-database-db-postgresql
  namespace: default
  annotations:
    render.crossplane.io/composition-path: apis/postgresql/composition.yaml
    render.crossplane.io/function-path: examples/function/function.yaml
spec:
  compositionSelector:
    matchLabels:
      dbengine: postgres
  parameters:
    region: westus
    storageGB: 5 #Minimum value is 5
    version: "11"
    passwordSecretRef:
      namespace: default
      name: psqlsecret
      key: password
    networkRef:
      id: configuration-azure-database #This field must match the XNetwork XR spec.parameters.id
  writeConnectionSecretToRef:
    name: configuration-azure-database-db-conn-postgresql
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: psqlsecret
  namespace: default
type: Opaque
