apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: sqlinstances.azure.platform.upbound.io
spec:
  scope: Namespaced
  group: azure.platform.upbound.io
  names:
    kind: SQLInstance
    plural: sqlinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                writeConnectionSecretToRef:
                  type: object
                  description: Connection secret reference for database credentials
                  properties:
                    name:
                      type: string
                      description: Name of the connection secret
                  required:
                    - name
                parameters:
                  type: object
                  properties:
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    managementPolicies:
                      description: ManagementPolicies for Azure Database resources. Defaults to ["*"] which includes all operations (Create, Observe, Update, Delete, LateInitialize). To orphan resources on deletion, use ["Create", "Observe", "Update", "LateInitialize"].
                      type: array
                      items:
                        type: string
                        enum:
                          - "*"
                          - Create
                          - Observe
                          - Update
                          - Delete
                          - LateInitialize
                      default: ["*"]
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    storageGB:
                      type: integer
                      description: Database size
                    version:
                      type: string
                      description: Database version
                    passwordSecretRef:
                      type: object
                      description: "A reference to the Secret object containing database password"
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                      required:
                        - name
                        - key
                    networkRef:
                      type: object
                      description: "A reference to the XNetwork object that this Database should be connected to."
                      properties:
                        id:
                          type: string
                          description: ID of the Network object this ref points to.
                      required:
                        - id
                  required:
                    - storageGB
                    - passwordSecretRef
                    - version
              required:
                - parameters
