apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xmariadbinstances.azure.platform.upbound.io
  labels:
    dbengine: mariadb
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: azure.platform.upbound.io/v1alpha1
    kind: XSQLInstance
  mode: Pipeline
  pipeline:
    - functionRef:
        name: upbound-configuration-azure-databasemariadb
      step: mariadb
    - functionRef:
        name: crossplane-contrib-function-auto-ready
      step: crossplane-contrib-function-auto-ready
